include:
  - board: akdk_bt1
    shield: split_ergo40pct_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: akdk_bt1
    shield: split_ergo40pct_right
    snippet:
      - studio-rpc-usb-uart
      - zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: akdk_bt1
    shield: settings_reset
