include:
  - board: akdk_bt1
    shield: split_ergo40pct_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    snippet: zmk-usb-logging
  - board: akdk_bt1
    shield: split_ergo40pct_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    snippet: zmk-usb-logging
  - board: akdk_bt1
    shield: settings_reset
