CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_POINTING=y
CONFIG_PAW3222=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

CONFIG_INPUT=y

CONFIG_PAW32XX_MAX_DEVICES=4  # 最大センサー数（デフォルト: 4）
CONFIG_PAW32XX_TOGGLE_ACCEL_KEYCODE=0xF0  # 加速度切り替え用F23キー
CONFIG_PAW32XX_TOGGLE_ACCEL_DEVICE_SELECT=y  # センサー選択モードを有効化
CONFIG_PAW32XX_TOGGLE_ACCEL_DEVICE_SELECT_KEYCODE=0xF1  # センサー選択用F24キー
