name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.2.1

  extract:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure .build directory exists
        run: mkdir -p .build

      - name: Download firmware artifacts
        uses: actions/download-artifact@v4
        with:
          name: firmware
          path: .build/firmware

      - name: Copy all files to .build
        run: |
          cp -r .build/firmware/* .build/
